version: "3"
services:
  mongoapi:
    image: "sebchevre/mongoapi:1.5"
    ports:
      - "9998:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - MONGODB_URL=mongodb://mongodb:27017 
      - ASPNETCORE_URLS=https://+;http://+
       - PIPEDREAM_URL=https://31301cce0d381d6c9338a006d3d31044.m.pipedream.net
  mongodb:
    container_name: mongodb
    image: "mongo"
    ports: 
      - "27017:27017"


  