apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mongoapi-env
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-data
  name: grafana-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
