apiVersion: v1
kind: Service
metadata:
  namespace: mongoapi-env
  annotations:
  creationTimestamp: null
  labels:
    service: mongoapi
  name: mongoapi-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: mongoapi
status:
  loadBalancer: {}

