apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mongoapi-env
  annotations:
    kompose.cmd: C:\dev\kompose\kompose.exe --file .\docker-compose-prometheus.yml
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongoapi
  name: mongoapi
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: mongoapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongoapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: MONGODB_URL
          value: mongodb://mongodb:27017
        - name: PIPEDREAM_URL
          value: https://31301cce0d381d6c9338a006d3d31044.m.pipedream.net
        image: sebchevre/mongoapi:1.8.1-http
        name: mongoapi
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}