apiVersion: v1
kind: Service
metadata:
  namespace: mongoapi-env
  annotations:
  creationTimestamp: null
  labels:
    service: prometheus
  name: prometheus
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
status:
  loadBalancer: {}
