apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\dev\kompose\kompose.exe --file .\docker-compose-prometheus.yml
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
status: {}
